name: Wallet CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    container: damingondiwa/computational-workflows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 -m pytest

